[WIP] feat: add article page
sanctuarycomputer/uniswap-support-redesigned pull request #25
Opened 2024-11-01 15:53 UTC by limsohee1002

### Description

### Type(s) of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Update to an existing feature

### Motivation for PR

### How Has This Been Tested?

### Applicable screenshots

### Follow-up PR

2024-11-04 12:30 UTC, mokaymokay approved these changes

2024-11-04 12:30 UTC, mokaymokay commented on src/modules/article-page/ArticlePageModule.tsx
> +export const ArticleBreadcrumbs: FC<Props> = ({ articlePageData }) => {
I'm not seeing breadcrumbs in the preview.. is this data available on the page? why isn't it shown?

2024-11-04 15:19 UTC, limsohee1002 commented on src/modules/article-page/ArticlePageModule.tsx
> +export const ArticleBreadcrumbs: FC<Props> = ({ articlePageData }) => {
oh that is bug I missed that! I will update it!

2024-11-04 15:33 UTC, nahbee10 requested changes
- did you also add image module in this PR? Images are rendered in this way, without any vertical paddings and the gray background(with icon+caption) as [the design](https://www.figma.com/design/QkBERlCkBKBAWRqELCC8uq/%5BUniswap%5D-%F0%9F%8D%84-Spore-Library-w%2F-Web?m=auto&node-id=5046-18654)
<img width="1290" alt="Screenshot 2024-11-02 at 11 49 48 AM" src="https://github.com/user-attachments/assets/22230058-f9fd-4dfa-8734-795a8d2d3e8f">

2024-11-04 15:33 UTC, nahbee10 commented on src/modules/homepage/HomepageModule.tsx
> +      <div className="transition opacity-0 group-hover:opacity-100">
this creates a bit of regression on the short description items: 
<img width="513" alt="Screenshot 2024-11-02 at 11 51 25 AM" src="https://github.com/user-attachments/assets/e1b782a0-c589-4092-9dd0-c60a75d090df">

2024-11-04 15:33 UTC, nahbee10 commented
- also noticed this bug on the theme switcher on mobile. will add this to the QA items: 
<img width="883" alt="Screenshot 2024-11-02 at 11 46 29 AM" src="https://github.com/user-attachments/assets/f2bc76ae-fbe9-4fbf-9cf8-2f1861aa88bd">

2024-11-04 16:03 UTC, nahbee10 commented
> * did you also add image module in this PR? Images are rendered in this way, without any vertical paddings and the gray background(with icon+caption) as [the design](https://www.figma.com/design/QkBERlCkBKBAWRqELCC8uq/%5BUniswap%5D-%F0%9F%8D%84-Spore-Library-w%2F-Web?m=auto&node-id=5046-18654)
> 
https://uniswaplabs.zendesk.com/auth/v2/login/signin?return_to=https%3A%2F%2Funiswaplabs1730152595.zendesk.com%2Fhc%2Fen-us%2Farticles%2F31449357746573-What-are-these-sections-and-articles-doing-here&theme=hc&locale=en-us&brand_id=31433470015629&auth_origin=31433470015629%2Cfalse%2Ctrue

2024-11-04 18:20 UTC, limsohee1002 commented
![image](https://github.com/user-attachments/assets/59f139c9-5308-4e66-bb62-ef0977e43e59)
this is image on 
https://uniswaplabs.zendesk.com/hc/en-us/articles/17674084283149-How-to-swap-on-UniswapX
this article. The caption is part of the image, and we can't really render it separately...
https://uniswaplabs.zendesk.com/hc/article_attachments/24477317213581

2024-11-04 18:22 UTC, limsohee1002 commented
> * did you also add image module in this PR? Images are rendered in this way, without any vertical paddings and the gray background(with icon+caption) as [the design](https://www.figma.com/design/QkBERlCkBKBAWRqELCC8uq/%5BUniswap%5D-%F0%9F%8D%84-Spore-Library-w%2F-Web?m=auto&node-id=5046-18654)
> 
> <img alt="Screenshot 2024-11-02 at 11 49 48 AM" width="1290" src="https://private-user-images.githubusercontent.com/12539032/382815426-22230058-f9fd-4dfa-8734-795a8d2d3e8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MzY0MTcsIm5iZiI6MTczMDczNjExNywicGF0aCI6Ii8xMjUzOTAzMi8zODI4MTU0MjYtMjIyMzAwNTgtZjlmZC00ZGZhLTg3MzQtNzk1YThkMmQzZThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE2MDE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MTdlMjliZDM1YjU4YTE2MTAxOWZkZDBiYTI4ZjdiNWE1OWNiNzM5MzRjNWQ0ZDlmM2ZjOTJmNmQyMGYxN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.chwEdrwtjxxWdzw6QE-jb7nEmQ4cIcGxocd7bC5bk9g">

The link on the image doesn't seem to work anymore...
https://uniswaplabs.zendesk.com/hc/en-us/articles/31449357746573-What-are-these-sections-and-articles-doing-here

2024-11-05 19:00 UTC, limsohee1002 commented
Updated preview!:
https://www.loom.com/share/89b25eede3fe4e14b425ecccf0d7d45d?sid=af11d0de-3b83-42e0-9989-ab8dc0d6cdf3

2024-11-05 20:03 UTC, merged