feat: add side nav and 404 page
sanctuarycomputer/uniswap-support-redesigned pull request #29
Opened 2024-11-05 22:20 UTC by limsohee1002

### Description
- add side nav
- add side nav api
- add local storage to save side nav data
- add 404 page

### Type(s) of changes

- [ ] Bug fix
- [x] New feature
- [ ] Update to an existing feature

### Motivation for PR
#26 #16 

### Applicable screenshots
https://www.loom.com/share/621e215a90fb4e9a9bce5bd50f060350?sid=958c8a51-a045-4cff-a1a5-d890e3f37f6c

2024-11-06 20:28 UTC, nahbee10 requested changes
This overlap issue still happening! Will document this on QA ticket, let's address this later in the QA phase. 
I've added one comment about make the inactive category items are also clickable

2024-11-06 20:28 UTC, nahbee10 commented on src/modules/side-nav/SideNavModule.tsx
> +                </h3>
I think these category headings should also be clickable:
https://www.loom.com/share/96544e49e4064d78a86898d77d7b18e6?sid=2fe406d9-4a1d-40f6-9cdb-ac5657f6d2af

2024-11-06 20:30 UTC, nahbee10 commented
Also noticed that we need to adjust heading level which is used by right side nav('On this page') for jump links. For now it's using too much of body text I think: 
<img width="1108" alt="Screenshot 2024-11-06 at 3 21 34 PM" src="https://github.com/user-attachments/assets/760f4cb4-1989-4ac7-9430-d8006a3ce380">

2024-11-06 22:14 UTC, limsohee1002 commented on src/modules/side-nav/SideNavModule.tsx
> +                </h3>
I updated it! on nav, I think we should go though hover state with designer. I felt like it is not consistant but I guess we can handle that on QA!

2024-11-06 22:17 UTC, limsohee1002 commented
> Also noticed that we need to adjust heading level which is used by right side nav('On this page') for jump links. For now it's using too much of body text I think: <img alt="Screenshot 2024-11-06 at 3 21 34 PM" width="1108" src="https://private-user-images.githubusercontent.com/12539032/383716144-760f4cb4-1989-4ac7-9430-d8006a3ce380.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MzA3MzIsIm5iZiI6MTczMDkzMDQzMiwicGF0aCI6Ii8xMjUzOTAzMi8zODM3MTYxNDQtNzYwZjRjYjQtMTk4OS00YWM3LTk0MzAtZDgwMDZhM2NlMzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDIyMDAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NTUyMGMxNTZlOTc0MzA2YWE0MDlmOTYyNGNhOGU5YTRiOWVjZDIyYzk1OTViMmMzNjM5ZTI1OGEzNjdhZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tZoTb6A9LaZUMYAipayoKyTSvAlqd1TewUVbR4pVTIM">

right now, I am grabbing header 1 to 4 to add to side navigation. I think we should ask editor how they imagine to use that. If they would like us to only grab 1 to 3, we can do that as well, but I have seen some h4 that have different text sizes that are represented as titles, so let's confirm with the editor!
It is a super easy fix, if they want us to use h4 as side nav title, they should update this article so I think it will be good to confirm first

2024-11-07 02:46 UTC, nahbee10 approved these changes
We also need to add side nav items to the mobile nav modal([design](https://www.figma.com/design/QkBERlCkBKBAWRqELCC8uq/%5BUniswap%5D-%F0%9F%8D%84-Spore-Library-w%2F-Web?m=auto&node-id=5046-19167)). Let's handle it in the separate PR.
<img width="367" alt="Screenshot 2024-11-06 at 9 44 45 PM" src="https://github.com/user-attachments/assets/a7abadf7-fb63-4039-ad4d-2efb27328bd9">

2024-11-07 11:45 UTC, mokaymokay approved these changes
Nice work! Just a couple small things. No additional comments besides Nahee's

2024-11-07 14:33 UTC, limsohee1002 commented on src/modules/side-nav/SideNavModule.tsx
> +                  }
It is not actually first element inside of the div 🥲 it has button div above it so I just added that ☺️

2024-11-07 14:39 UTC, merged